/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <main.h>

unsigned short data[7] = {1000, 2000, 3000, 4000, 5000, 6000, 7000};
unsigned char data1[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
unsigned char data2[10] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};


int main(void)
{

	enable_RCC_APB2ENR(APB2_TIM1);
	enable_RCC_APB2ENR(APB2_PORT_A);
	GPIO_Mode(GPIOA, 8, GPIO_MODE_AF_OUTPUT_PUSHPULL_50MHz);

//	TIM1->TIMx_CCMR1.REG |= 6 << 4 ;
//	TIM1->TIMx_BDTR.REG |= 1 << 15 | 1 << 11;
//
//	TIM1->TIMx_CCER.REG |= 1;
//	TIM1->TIMx_CCR1.REG = 2000;
//	TIM1->TIMx_ARR.REG  = 7999;
//	TIM1->TIMx_EGR.REG = 1;
//
//	TIM1->TIMx_DIER.REG |= 1 << 8;
//	TIM1->TIMx_CR1.REG |= 1 << 7 | 1 << 2 | 1;
//
//	RCC->RCC_AHBENR.REG |= 1;
//	DMA->DMA_CMAR1.REG = (unsigned long) &TIM1->TIMx_CCR1.REG;
//	DMA->DMA_CPAR1.REG = (unsigned long) &data;
//	DMA->DMA_CNDTR1.REG |= 7;
//	DMA->DMA_CCR1.REG |= 1 << 10 | 1 << 8 |  1 << 7 |1 << 5 |1 << 4 | 1;

//	DMA->DMA_CNDTR1.REG = 7;
//	DMA->DMA_CCR1.REG = 1 << 10 | 1 << 8 |  1 << 7 |1 << 5 |1 << 4 | 1;
//

//	enable_RCC_APB2ENR(APB2_PORT_A);
//	GPIO_Mode(GPIOA, 0, GPIO_MODE_OUTPUT_PUSHPULL_50MHz);
//	GPIO_Mode(GPIOA, 1, GPIO_MODE_OUTPUT_PUSHPULL_50MHz);
//	GPIO_Mode(GPIOA, 2, GPIO_MODE_OUTPUT_PUSHPULL_50MHz);
//
//	RCC->RCC_AHBENR.REG = 1;
//
//	DMA->DMA_CMAR1.REG = (unsigned long) &GPIOA->ODR.REG;
//	DMA->DMA_CPAR1.REG = (unsigned long) &data1;
//	DMA->DMA_CNDTR1.REG = 10;
//	DMA->DMA_CCR1.REG = 1 << 14 | 1 << 7 | 1 << 6 | 1;

//	RCC->RCC_AHBENR.REG = 1;
//
//	DMA->DMA_CMAR1.REG = (unsigned long) &data2;
//	DMA->DMA_CPAR1.REG = (unsigned long) &data1;
//	DMA->DMA_CNDTR1.REG = 10;
//	DMA->DMA_CCR1.REG = 1 << 14 | 1 << 7 | 1 << 6 | 1;

    /* Loop forever */
	while(1){

	}
}
