/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <main.h>

void delay_ms(unsigned long ms) {
    for (unsigned long i = 0; i < ms*1000; i++) {
        __asm("nop");
    }
}

void uart1_send_char(char c) {

	while( !(USART1->USART_SR.BITS.TXE));
	USART1->USART_DR.REG = c;
}

void uart1_send_string(char *str, int len) {
    for (int i = 0; i < len; i++) {
        uart1_send_char(str[i]);
    }
}

int _write(int file, char *ptr, int len)
{
    uart1_send_string( ptr,len);
    return len;
}

void USART1_IRQHandler(void) {
	if(USART1->USART_SR.BITS.RXNE){
		char received_data = USART1->USART_DR.REG;
		USART1->USART_DR.REG = received_data;
	}
}


int main(void)
{
	enable_RCC_APB2ENR(APB2_PORT_A | APB2_USART1);
	GPIO_Mode(GPIOA, 9, GPIO_MODE_AF_OUTPUT_PUSHPULL_50MHz);
	GPIO_Mode(GPIOA, 10, GPIO_MODE_INPUT_FLOAT);

	USART1->USART_BRR.REG = 0x0341;

	USART1->USART_CR1.REG = 1 << 13 | 1 << 5| 1 << 3 | 1 << 2;

	*((unsigned long *) 0xE000E104) = (1 << (37 - 32));

    /* Loop forever */
	while(1){
		delay_ms(500);
	}
}
