/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <main.h>


void TIM1_UP_IRQHandler(){
	TIM1->TIMx_SR.REG = 0;
	GPIO_Toggle(GPIOC, 13);
}

int main(void)
{
	enable_RCC_APB2ENR(APB2_PORT_C);
	enable_RCC_APB2ENR(APB2_TIM1);
	enable_RCC_APB2ENR(APB2_PORT_A);

	// PWM software
//	GPIO_Mode(GPIOC, 13, GPIO_MODE_OUTPUT_OPEN_50MHz);
//	TIM1->TIMx_CR2.REG  = 0;
//	TIM1->TIMx_SMCR.REG = 0;
//	TIM1->TIMx_DIER.REG = 1;
//	TIM1->TIMx_ARR.REG  = 7999;
//	TIM1->TIMx_CR1.REG |= 1 << 7 | 1 << 2 | 1;
//
//	*((unsigned long *) 0xE000E100)  = 1 << 25; // enable NVIC

	// PWM register
	GPIO_Mode(GPIOA, 8, GPIO_MODE_AF_OUTPUT_PUSHPULL_50MHz);

	TIM1->TIMx_CCMR1.REG |= 6 << 4 ;
	TIM1->TIMx_CCMR1.REG &= ~1;
	TIM1->TIMx_BDTR.REG |= 1 << 15 | 1 << 10 | 1 << 11;

	TIM1->TIMx_CCER.REG |= 1;
	TIM1->TIMx_CCR1.REG = 1000;
	TIM1->TIMx_ARR.REG  = 7999;
	TIM1->TIMx_EGR.REG = 1;
	TIM1->TIMx_CR1.REG |= 1 << 7 | 1 << 2 | 1;
    /* Loop forever */
	while(1){

	}
}
