/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <main.h>

void SysTick_Handler(){
	GPIO_Toggle(GPIOC, 13);
}

int main(void)
{
	RCC->RCC_APB2ENR.REG |= 1 << 4;
	GPIO_Mode(GPIOC, 13, GPIO_MODE_OUTPUT_OPEN_50MHz);

	STK.VAL = 100; // write any value to reset counter
	STK.LOAD = 7999999; // 1s

	STK.CTRL.REG |= (1 << 2) | (1 << 1) | 1;
    /* Loop forever */
	while(1){

	}
}
