/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <main.h>
#define GPIOC_ODR_BB_ADDR 0x2200010C
void delay_ms(unsigned long ms) {
    for (unsigned long i = 0; i < ms*1000; i++) {
        __asm("nop");
    }
}
int main(void)
{
 	RCC_APB2ENR |= RCC_IOPCEN;
 	GPIO_Mode(GPIOC, 13, GPIO_MODE_OUTPUT_OPEN_50MHz);
 	// bit band

 	uint8_t *alias_addr_PC13 = (uint8_t *)(0x42000000 + (32 * (0x40011010 - 0x40000000)) + 13 * 4);

 	uint8_t *alias_addr_PC13_1 = (uint8_t *)(0x42000000 + (32 * (0x40011010 - 0x40000000)) + (13+16) * 4);

//  Use ODR register
// 	uint8_t *alias_addr_PC13 = (uint8_t *)(0x42000000 + (32 * (0x4001100C - 0x40000000)) + 13 * 4);
// 	*alias_addr_PC13 = 1;
// 	*alias_addr_PC13 = 0;
 	while(1){

 		// Use BSRR register
 	 	*alias_addr_PC13 = 1;
 	 	delay_ms(200);
 	 	*alias_addr_PC13_1 = 1;
		delay_ms(200);
 	}
}
