/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <main.h>

void delay_ms(unsigned long ms) {

    for (unsigned long i = 0; i < ms*1000; i++) {
        __asm("nop");
    }
}
unsigned long test ;
int main(void)
{

	FLASH->FLASH_ACR.REG |= 2;

	RCC->RCC_CR.REG |= 1 << 16;
	while(!RCC->RCC_CR.BITS.HSERDY);

	RCC->RCC_CFGR.REG |= 9 << 18;
	RCC->RCC_CFGR.REG |= 1 << 16;

	RCC->RCC_CR.REG |= 1 << 24;
	while(!RCC->RCC_CR.BITS.PLL_RDY);

	RCC->RCC_CFGR.BITS.SW = 2;
	while(RCC->RCC_CFGR.BITS.SWS != 2);


//	RCC->RCC_CFGR.REG = 4 << 24;
	RCC->RCC_APB2ENR.REG |= 1 << 4; // enable RCC GPIOC
//	RCC->RCC_APB2ENR.REG |= 1 << 2; // enable RCC GPIOA
//	GPIO_Mode(GPIOA, 8, GPIO_MODE_AF_OUTPUT_PUSHPULL_50MHz);
	GPIO_Mode(GPIOC, 13, GPIO_MODE_OUTPUT_OPEN_50MHz);

    /* Loop forever */
	while(1){
		GPIO_Toggle(GPIOC, 13);
		delay_ms(1000);
	}
}
