/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <main.h>

int main(void)
{
	enable_RCC_APB1ENR(APB1_I2C1);
	I2C1->I2C_CCR.REG = 0x50;
	I2C1->I2C_TRISE.REG = 0x09;

	I2C1->I2C_CR1.REG |= 1;
	I2C1->I2C_CR1.REG |= 1 << 8;


    /* Loop forever */
	while(1){

	}
}
