/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <main.h>


void delay_ms(unsigned long ms) {
    for (unsigned long i = 0; i < ms*1000; i++) {
        __asm("nop");
    }
}

unsigned long test;
unsigned long test1;
unsigned long test2;
unsigned long test3;
unsigned long test4;
int main(void)
{
 	RCC_APB2ENR |= RCC_IOPCEN;
 	test = GPIOC->CRL.REG;
// 	GPIOC->CRH.REG |= 1UL << 20 | 1UL << 21;
// 	GPIOC->CRH.REG &= ~(1 <<22) & ~(1 << 23);

// 	test1 = GPIOC->CRH.REG;
// 	test2 = GPIOC->CRL.REG;

 	GPIO_Mode(GPIOC, 1UL << 13, GPIO_MODE_OUTPUT_PUSHPULL_50MHz);

 	test3 = GPIOC->CRH.REG;
 	test4 = GPIOC->CRL.REG;
    /* Loop forever */
	while(1){
		GPIOC->ODR.REG |= 1 << 13;
//		GPIOC->ODR.BITS.b13 = !GPIOC->ODR.BITS.b13;
		delay_ms(100);
		GPIOC->ODR.REG &= ~(1 << 13);
		delay_ms(100);
//		GPIOC->BSRR.REG = (1UL << 13);
//		delay_ms(100);
//		GPIOC->BSRR.REG = (1UL << (13 + 16));
//		delay_ms(100);
	}
}
