/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <main.h>
#include <stddef.h>

void delay_ms(unsigned long ms) {
    for (unsigned long i = 0; i < ms*1000; i++) {
        __asm("nop");
    }
}

size_t size;

int main(void)
{
 	RCC_APB2ENR |= RCC_IOPCEN;
	GPIOC->CRH.BITS.MODE_13 = 3;
	GPIOC->CRH.BITS.CNF_13 = 0;

    /* Loop forever */
	while(1){
//		GPIOC->ODR.REG = ~ GPIOC->ODR.REG;
		GPIOC->ODR.BITS.b13 = !GPIOC->ODR.BITS.b13;
		delay_ms(100);

//		GPIOC->BSRR.REG = (1UL << 13);
//		delay_ms(100);
//		GPIOC->BSRR.REG = (1UL << (13 + 16));
//		delay_ms(100);
	}
}
