/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <main.h>


void delay_ms(unsigned long ms) {
    for (unsigned long i = 0; i < ms*1000; i++) {
        __asm("nop");
    }
}
GPIO_STATE test;

int main(void)
{
 	RCC_APB2ENR |= RCC_IOPCEN;

// 	GPIOC->CRH.REG |= 1UL << 20 | 1UL << 21;
// 	GPIOC->CRH.REG &= ~(1 <<22) & ~(1 << 23);
 	GPIO_Mode(GPIOC, 13, GPIO_MODE_OUTPUT_OPEN_50MHz);
 	GPIO_Mode(GPIOC, 14, GPIO_MODE_INPUT_PULL);
    /* Loop forever */
	while(1){

		test = GPIO_Read(GPIOC,14);
//		GPIOC->ODR.REG |= 1 << 13;
//		GPIO_Write(GPIOC,13,GPIO_SET);

//		GPIOC->ODR.BITS.b13 = !GPIOC->ODR.BITS.b13;
		GPIO_Toggle(GPIOC, 13);
		delay_ms(100);
//		GPIO_Write(GPIOC,13,GPIO_RESET);
////
//		delay_ms(200);
//		GPIOC->BSRR.REG = (1UL << 13);
//		delay_ms(100);
//		GPIOC->BSRR.REG = (1UL << (13 + 16));
//		delay_ms(100);
	}
}
